[general]
host = "0.0.0.0"
port = 6432
enable_prometheus_exporter = true
prometheus_exporter_port = 9930
connect_timeout = 500
healthcheck_timeout = 1000
healthcheck_delay = 30000
shutdown_timeout = 1
ban_time = 60 # seconds
autoreload = false
admin_username = "admin_user"
admin_password = "admin_pass"

[pools.sharded_db]
pool_mode = "transaction"
default_role = "any"
query_parser_enabled = true
primary_reads_enabled = true
sharding_function = "pg_bigint_hash"
[pools.sharded_db.users.0]
username = "sharding_user"
password = "sharding_user"
pool_size = 1
statement_timeout = 0
[pools.sharded_db.shards.0]
servers = [
    [ "127.0.0.1", 5432, "primary" ],
]
database = "shard0"
